Update TypeScript and @atomist/automation-client
Update to TypeScript 2.9.2.  Compilation failed on the antlr4ts
generated parsers.  For example:

```
lib/tree/ast/antlr/kotlin/antlr-gen/KotlinParser.ts:17395:3 - error TS2345: Argument of type 'TypedPropertyDescriptor<() => SemiContext>' is not assignable to parameter of type 'TypedPropertyDescriptor<(...args: any[]) => ParserRuleContext>'.
  Types of property 'set' are incompatible.
    Type '(value: () => SemiContext) => void' is not assignable to type '(value: (...args: any[]) => ParserRuleContext) => void'.
      Types of parameters 'value' and 'value' are incompatible.
        Type 'ParserRuleContext' is not assignable to type 'SemiContext'.

17395  @RuleVersion(0)
        ~~~~~~~~~~~~~~
```

The RuleVersion annotation function is empty and commenting out the
lines with the annotation allowed compilation and tests to complete
successfully.

Update TypeScript and TSLint configurations to be more in line with
other projects.  Fix issues that arise, including installing missing
dependencies.  It is not possible to set the TypeScript compiler
noUnusedLocals option as the ANTLR generated TypeScript has many of
them.

Update to @atomist@automation-client@1.0.0-M.2.  Clean up test output.